version: "3.2"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kafka_net
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "mytopic_1:1:1,mytopic_2:1:1"
      KAFKA_ADVERTISED_HOST_NAME: kafka
    networks:
      - kafka_net
  provider:
    build: ./pruebaKafka
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    networks:
      - kafka_net
  listener:
    build: ./pruebaKafka2
    ports:
      - "8081:8080"
    depends_on:
      - kafka
    networks:
      - kafka_net
networks:
  kafka_net:
    driver: bridge